### ISSUE TITLE
Add docker-compose.yml

### ISSUE THREAD

**Issue by domenukk** [TheFynx/docker-weechat#3]
I suggest adding a `docker-compose.yml` file to the docu or the repo.
With this example from below inside my weechat folder, I can simply `docker-compose up -d` and it works. 
```yaml
version: '3'
services:
  weechat:
    image: thefynx/alpine-weechat
    ports:
     - "9001:9001"
    volumes:
     - ./:/weechat/.weechat
    stdin_open: true
    tty: true
```
